package codes
import org.junit.runner.RunWith
import org.junit.Test
import org.junit.Assert._

class RailFenceTest {

  @Test
  def encode() {

    assertEquals("LEIFRORJLAESLENIEADNEIAAUANRTPDINDISTPENMVTEAURMUEIESNLXNEASRCTENTOECIA", RailFence.encode("LANATUREESTREMPLIEDUNEINFINITEDERAISONSDONTLEXPERIENCENAJAMAISVULATRACE", 8));
  }

  @Test
  def decode() {
    assertEquals("LANATUREESTREMPLIEDUNEINFINITEDERAISONSDONTLEXPERIENCENAJAMAISVULATRACE", RailFence.decode("LEIFRORJLAESLENIEADNEIAAUANRTPDINDISTPENMVTEAURMUEIESNLXNEASRCTENTOECIA", 8));
  }

}